/* USER */

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_SETTING = "USER_SETTING";
export const USER_SETTING_SUCCESS = "USER_SETTING_SUCCESS";
export const USER_SETTING_FAILURE = "USER_SETTING_FAILURE";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_EDIT = "USER_EDIT";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAILURE = "USER_EDIT_FAILURE";

export const USER_DELETE = "USER_DELETE";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAILURE = "USER_DELETE_FAILURE";

export const USER_LIST = "USER_LIST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_GET_STATUS = "USER_GET_STATUS";
export const USER_GET_STATUS_SUCCESS = "USER_GET_STATUS_SUCCESS";
export const USER_GET_STATUS_FAILURE = "USER_GET_STATUS_FAILURE";

export const USER_SEARCH = "USER_SEARCH";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILURE = "USER_SEARCH_FAILURE";

/* MEAL */
export const MEAL_CREATE = "MEAL_CREATE";
export const MEAL_CREATE_SUCCESS = "MEAL_CREATE_SUCCESS";
export const MEAL_CREATE_FAILURE = "MEAL_CREATE_FAILURE";

export const MEAL_LIST = "MEAL_LIST";
export const MEAL_LIST_SUCCESS = "MEAL_LIST_SUCCESS";
export const MEAL_LIST_FAILURE = "MEAL_LIST_FAILURE";

export const MEAL_EDIT = "MEAL_EDIT";
export const MEAL_EDIT_SUCCESS = "MEAL_EDIT_SUCCESS";
export const MEAL_EDIT_FAILURE = "MEAL_EDIT_FAILURE";

export const MEAL_DELETE = "MEAL_DELETE";
export const MEAL_DELETE_SUCCESS = "MEAL_DELETE_SUCCESS";
export const MEAL_DELETE_FAILURE = "MEAL_DELETE_FAILURE";

export const MEAL_SEARCH = "MEAL_SEARCH";
export const MEAL_SEARCH_SUCCESS = "MEAL_SEARCH_SUCCESS";
export const MEAL_SEARCH_FAILURE = "MEAL_SEARCH_FAILURE";
